version: '3.8'

services:

  ente-creditore:
    image: 'ente-creditore:latest'
    build:
      context: ./ente-creditore
    ports:
      - "8082:8082"
    container_name: ente-creditore
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/entec
      - SPRING_DATASOURCE_USERNAME=postgres-user-test
      - SPRING_DATASOURCE_PASSWORD=postgres-pwd-test
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - hubpa-net
  
  service-managment:
    image: 'service-managment:latest'
    build:
      context: ./service-managment
    ports:
      - "8083:8083"
    container_name: service-managment
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/sermng
      - SPRING_DATASOURCE_USERNAME=postgres-user-test
      - SPRING_DATASOURCE_PASSWORD=postgres-pwd-test
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_CORS_ORIGINS=http://localhost:8083,http://service-managment:8083
    networks:
      - hubpa-net
  
  upload-payments:
    env_file: "./upload-payments/.env"
    image: 'upload-payments:latest'
    build:
      context: ./upload-payments
    ports:
      - "8084:8084"
    container_name: upload-payments
    depends_on:
      - postgres
    networks:
      - hubpa-net
      
  
  queue-worker:
    env_file: "./queue-worker/.env"
    image: 'queue-worker:latest'
    build:
      context: ./queue-worker
    ports:
      - "8086:8086"
    container_name: queue-worker
    networks:
      - hubpa-net

  payments:
    env_file: "./payments/.env"
    image: 'payments:latest'
    build:
      context: ./payments
    ports:
      - "8085:8085"
    container_name: payments
    networks:
      - hubpa-net
    
  support:
    env_file: "./support/.env"
    image: 'support:latest'
    build:
      context: ./support
    ports:
      - "8087:8087"
    container_name: support
    
  hub-spid-login-ms:
    container_name: hub-spid-login-ms
    image: 'hub-spid-login-ms:latest'
    build:
      context: ./hub-spid-login-ms
      dockerfile: ./Dockerfile
    env_file: "./hub-spid-login-ms/.env"
    # expose:
    #   - "9090"
    ports:
      - "9090:8080"
    depends_on:
      - redis
    networks:
      - hubpa-net
    

  spid-testenv2:
    image: italia/spid-testenv2:1.1.0
    ports:
      - "8088:8088"
    volumes:
      - "./hub-spid-login-ms/conf-testenv:/app/conf"
      - "./hub-spid-login-ms/certs:/app/certs:ro"
    depends_on: 
      - hub-spid-login-ms
    networks:
      - hubpa-net

  
  redis:
    container_name: redis
    image: wodby/redis:3.2-2.1.5
    environment:
      REDIS_TIMEOUT: 300
      REDIS_TCP_KEEPALIVE: 60
      REDIS_MAXMEMORY: 182m
    networks:
      - hubpa-net
    
          
  postgres:
    image: 'postgres'
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh"
    environment:
      - POSTGRES_USER=postgres-user-test
      - POSTGRES_PASSWORD=postgres-pwd-test
    networks:
      - hubpa-net
      
  api-gateway:
    image: nginx
    ports:
      - "8000:8080"
    volumes:
      - "./api-gateway/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./api-gateway/tokenPolicy.js:/home/tokenPolicy.js:ro"
    networks:
      - hubpa-net

  
  # During integration tests use Azure Service Bus
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
networks:
  hubpa-net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
    