version: '3.8'

services:
  
  service-managment:
    env_file: "./service-managment/.env"
    image: 'service-managment:latest'
    build:
      context: ./service-managment
    ports:
      - "8083:8083"
    container_name: service-managment
    depends_on:
      - postgres
    networks:
      - hubpa-net
  
  upload-payments:
    env_file: "./upload-payments/.env"
    image: 'upload-payments:latest'
    build:
      context: ./upload-payments
    ports:
      - "8084:8084"
    container_name: upload-payments
    depends_on:
      - postgres
    networks:
      - hubpa-net
      
  
  queue-worker:
    env_file: "./queue-worker/.env"
    image: 'queue-worker:latest'
    build:
      context: ./queue-worker
    ports:
      - "8086:8086"
    container_name: queue-worker
    networks:
      - hubpa-net

  payments:
    env_file: "./payments/.env"
    image: 'payments:latest'
    build:
      context: ./payments
    ports:
      - "8085:8085"
    container_name: payments
    depends_on:
      - postgres
    networks:
      - hubpa-net
    
  postgres:
    image: postgres
    container_name: postgres
    build:
      context: ./postgres
    ports:
      - "5432:5432"
    # volumes:
    #   - "./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:Z"
    environment:
      - POSTGRES_USER=postgres_user_test
      - POSTGRES_PASSWORD=postgres_pwd_test
    networks:
      - hubpa-net
  
  # During integration tests use Azure Service Bus
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
networks:
  hubpa-net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
    