version: '3.8'

services:
  
  payments:
    env_file: "./payments/.env"
    image: 'payments:latest'
    build:
      context: ./payments
    ports:
      - "8085:8085"
    container_name: payments
    depends_on:
      - postgres
    networks:
      - hubpa-net
    
  postgres:
    image: postgres
    container_name: postgres
    build:
      context: ./postgres
    ports:
      - "5432:5432"
    # volumes:
    #   - "./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:Z"
    environment:
      - POSTGRES_USER=postgres_user_test
      - POSTGRES_PASSWORD=postgres_pwd_test
    networks:
      - hubpa-net
  
  # During integration tests use Azure Service Bus
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
networks:
  hubpa-net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
    