version: '3.8'

services:
  
  payments:
    env_file: "./payments/.env"
    image: 'payments:latest'
    build:
      context: ./payments
    ports:
      - "8085:8085"
    container_name: payments
    depends_on:
      - postgres
    networks:
      - hubpa-net
    
  postgres:
    image: postgres
    container_name: postgres
    build:
      context: ./postgres
    ports:
      - "5432:5432"
    # volumes:
    #   - "./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:Z"
    environment:
      - POSTGRES_USER=postgres_user_test
      - POSTGRES_PASSWORD=postgres_pwd_test
    networks:
      - hubpa-net
  
  service-managment:
    env_file: "./service-managment/.env"
    image: 'service-managment:latest'
    build:
      context: ./service-managment
    ports:
      - "8083:8083"
    container_name: service-managment
    depends_on:
      - postgres
    networks:
      - hubpa-net
      
networks:
  hubpa-net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
    