# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  
# Prepare Analysis Configuration task
- task: SonarQubePrepare@4
  inputs:
    SonarQube: $(SONARURL)
    scannerMode: 'Other'
    extraProperties: 'sonar.projectKey=$(SONARPRJKEY)'
    
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    options: '-DskipTests'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
#    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    sonarQubeRunAnalysis: true

# Publish Quality Gate Result task
- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'
