# Only manual triggers
trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

steps:

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: Docker@2
  inputs:
    containerRegistry: 'pagopa-azurecr'
    repository: 'creditor-institution'
    command: 'buildAndPush'
    Dockerfile: './ente-creditore/Dockerfile.deploy'
    tags: '0.0.1' 

# - task: AzureWebAppContainer@1
#   inputs:
#     azureSubscription: $(STAGING_AZURE_SUBSCRIPTION)
#     appName: 'hubpa-d-web-app1'
#     containers: 'hubpadarc.azurecr.io/microservices:ente-creditore'