package it.gov.pagopa.hubpa.payments.model.node;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.springframework.validation.annotation.Validated;
import javax.validation.constraints.*;

/**
 * - &#x60;id&#x60; : Subject issuing the error. Allowed values are : -
 * &#x60;NodoDeiPagamentiSPC&#x60; : constant which identifies the NodoSPC -
 * &#x60;[domain identifier]&#x60; : domain id of the creditor entity issuing
 * the fault - &#x60;[PSP identifier]&#x60; : PSP identifier issuing the fault -
 * &#x60;faultCode&#x60; : error code (see &#x60;stFaultCode&#x60; to details) -
 * &#x60;faultString&#x60; : Specification of the error code, specific to the
 * subject issuing it. Contains a more talking description relating to the
 * &#x60;faultCode&#x60;. - &#x60;description&#x60; : Additional description of
 * the error set by the NodoSPC, by the creditor or PSP. - &#x60;serial&#x60; :
 * Position of the element in the referenced list. Useful when providing a
 * parameter in the form of a vector (for example, in the primitive
 * &#x60;SendCarrelloRPT&#x60; node). If the error is generated by the EC or by
 * the PSP, the data reported is the value of the &#x60;faultBean.serial&#x60;
 * data set by the EC or by the PSP. - &#x60;originalFaultCode&#x60; : Error
 * code generated by the counterpart. (_Set only it isn&#39;t generated by
 * NodoSPC._) - &#x60;originalFaultString&#x60; : Specification of the error
 * code generated by the counterpart. (_Set only it isn&#39;t generated by
 * NodoSPC._) - &#x60;originalDescription&#x60; : Additional description of the
 * error generated by the counterparty. (_Set only it isn&#39;t generated by
 * NodoSPC._)
 */
@ApiModel(description = "- `id` : Subject issuing the error. Allowed values are :    - `NodoDeiPagamentiSPC` : constant which identifies the NodoSPC   - `[domain identifier]` : domain id of the creditor entity issuing the fault   - `[PSP identifier]` : PSP identifier issuing the fault  - `faultCode` : error code (see `stFaultCode` to details)  - `faultString` : Specification of the error code, specific to the subject issuing it. Contains a more talking description relating to the `faultCode`.  - `description` : Additional description of the error set by the NodoSPC, by the creditor or PSP.  - `serial` : Position of the element in the referenced list. Useful when providing a parameter in the form of a vector (for example, in the primitive `SendCarrelloRPT` node). If the error is generated by the EC or by the PSP, the data reported is the value of the `faultBean.serial` data set by the EC or by the PSP.  - `originalFaultCode` : Error code generated by the counterpart. (_Set only it isn't generated by NodoSPC._)  - `originalFaultString` : Specification of the error code generated by the counterpart. (_Set only it isn't generated by NodoSPC._)  - `originalDescription` : Additional description of the error generated by the counterparty. (_Set only it isn't generated by NodoSPC._)")
@Validated
public class CtFaultBeanTypePafn {

  @JsonProperty("faultCode")
  private String faultCode = null;

  @JsonProperty("faultString")
  private String faultString = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("serial")
  private Integer serial = null;

  @JsonProperty("originalFaultCode")
  private String originalFaultCode = null;

  @JsonProperty("originalFaultString")
  private String originalFaultString = null;

  @JsonProperty("originalDescription")
  private String originalDescription = null;

  public CtFaultBeanTypePafn faultCode(String faultCode) {
    this.faultCode = faultCode;
    return this;
  }

  /**
   * Get faultCode
   * 
   * @return faultCode
   **/
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public String getFaultCode() {
    return faultCode;
  }

  public void setFaultCode(String faultCode) {
    this.faultCode = faultCode;
  }

  public CtFaultBeanTypePafn faultString(String faultString) {
    this.faultString = faultString;
    return this;
  }

  /**
   * Get faultString
   * 
   * @return faultString
   **/
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public String getFaultString() {
    return faultString;
  }

  public void setFaultString(String faultString) {
    this.faultString = faultString;
  }

  public CtFaultBeanTypePafn id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * 
   * @return id
   **/
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CtFaultBeanTypePafn description(String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * 
   * @return description
   **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CtFaultBeanTypePafn serial(Integer serial) {
    this.serial = serial;
    return this;
  }

  /**
   * Get serial
   * 
   * @return serial
   **/
  @ApiModelProperty(value = "")
  public Integer getSerial() {
    return serial;
  }

  public void setSerial(Integer serial) {
    this.serial = serial;
  }

  public CtFaultBeanTypePafn originalFaultCode(String originalFaultCode) {
    this.originalFaultCode = originalFaultCode;
    return this;
  }

  /**
   * Get originalFaultCode
   * 
   * @return originalFaultCode
   **/
  @ApiModelProperty(value = "")
  public String getOriginalFaultCode() {
    return originalFaultCode;
  }

  public void setOriginalFaultCode(String originalFaultCode) {
    this.originalFaultCode = originalFaultCode;
  }

  public CtFaultBeanTypePafn originalFaultString(String originalFaultString) {
    this.originalFaultString = originalFaultString;
    return this;
  }

  /**
   * Get originalFaultString
   * 
   * @return originalFaultString
   **/
  @ApiModelProperty(value = "")
  public String getOriginalFaultString() {
    return originalFaultString;
  }

  public void setOriginalFaultString(String originalFaultString) {
    this.originalFaultString = originalFaultString;
  }

  public CtFaultBeanTypePafn originalDescription(String originalDescription) {
    this.originalDescription = originalDescription;
    return this;
  }

  /**
   * Get originalDescription
   * 
   * @return originalDescription
   **/
  @ApiModelProperty(value = "")
  public String getOriginalDescription() {
    return originalDescription;
  }

  public void setOriginalDescription(String originalDescription) {
    this.originalDescription = originalDescription;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CtFaultBeanTypePafn ctFaultBeanTypePafn = (CtFaultBeanTypePafn) o;
    return Objects.equals(this.faultCode, ctFaultBeanTypePafn.faultCode)
        && Objects.equals(this.faultString, ctFaultBeanTypePafn.faultString)
        && Objects.equals(this.id, ctFaultBeanTypePafn.id)
        && Objects.equals(this.description, ctFaultBeanTypePafn.description)
        && Objects.equals(this.serial, ctFaultBeanTypePafn.serial)
        && Objects.equals(this.originalFaultCode, ctFaultBeanTypePafn.originalFaultCode)
        && Objects.equals(this.originalFaultString, ctFaultBeanTypePafn.originalFaultString)
        && Objects.equals(this.originalDescription, ctFaultBeanTypePafn.originalDescription);
  }

  @Override
  public int hashCode() {
    return Objects.hash(faultCode, faultString, id, description, serial, originalFaultCode, originalFaultString,
        originalDescription);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CtFaultBeanTypePafn {\n");
    sb.append("    faultCode: ").append(toIndentedString(faultCode)).append("\n");
    sb.append("    faultString: ").append(toIndentedString(faultString)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    serial: ").append(toIndentedString(serial)).append("\n");
    sb.append("    originalFaultCode: ").append(toIndentedString(originalFaultCode)).append("\n");
    sb.append("    originalFaultString: ").append(toIndentedString(originalFaultString)).append("\n");
    sb.append("    originalDescription: ").append(toIndentedString(originalDescription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
