# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

version: '3.7'

services:
  queue-worker:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "9010:80"
    restart: always
    environment:
      AzureWebJobsStorage: ${STORAGE_CONNECTION_STRING}
      AzureWebJobsServiceBus: ${SB_CONNECTION_STRING}